### ISSUE TITLE
Extrinsic parameter between IMU and Camera

### ISSUE THREAD

**Issue by cyoahs** [ShuoYangRobotics/Cerberus#1]
Hello.

Does those parameter means the transformation from robot frame to camera frame? From the cfg and launch file I suppose that it might be some transformation from the robot base to the cam, but I'm not sure about the exact frames. 

Is the camera frame `camera_infra_frame` or `camera_infra_optical_frame`? (They are at the same position but different direction.)

Is the origin of the parent frame located at the center of the trunk? (I can not find another transform from the IMU frame to the body frame.)

**Comment by ShuoYangRobotics** [comment]
I assume robot body frame is located at COM and IMU is there too. The translation may not be accurate by the influence should be small.

**Comment by cyoahs** [comment]
> I assume robot body frame is located at COM and IMU is there too. The translation may not be accurate by the influence should be small.

Got it! Thx!
