### ISSUE TITLE
savitzky golay filter

### ISSUE THREAD

**Issue by niudix** [ShuoYangRobotics/Cerberus#19]
Hi, Shuo

While compiling the project, I found that savitzky golay filter is needed. I searched on github and found one from this [repo](https://github.com/arntanguy/gram_savitzky_golay). But when running the program, I encountered an error:
 "vilo: /usr/local/include/gram_savitzky_golay/gram_savitzky_golay.h:161: typename ContainerT::value_type gram_sg::SavitzkyGolayFilter::filter(const ContainerT&) const [with ContainerT = std::deque<double>; typename ContainerT::value_type = double]: Assertion `v.size() != weights_.size() || v.size() < 1' failed.
 
 I wonder if I downloaded the right version of the Savitzky-Golay filter.

**Comment by ShuoYangRobotics** [comment]
Please refer to the dockerfile (https://github.com/ShuoYangRobotics/Cerberus/blob/ad56c433a9a95aa47b1a436fb92c8e14c18965bd/.devcontainer/Dockerfile#L106)

**Comment by niudix** [comment]
> Please refer to the dockerfile (
> 
> https://github.com/ShuoYangRobotics/Cerberus/blob/ad56c433a9a95aa47b1a436fb92c8e14c18965bd/.devcontainer/Dockerfile#L106
> 
> )

Got it. The problem has been solved, thanks a lot.
