### ISSUE TITLE
Float value in foot force

### ISSUE THREAD

**Issue by cyoahs** [ShuoYangRobotics/Cerberus#2]
Hello.

From the bags I suppose that the `effort` in `/hardware_a1/joint_foot` is the foot force from `LowState`, but those values are of int16 type in unitree sdk and often postive. I found negative float values in the bag. Is there any conversions not included in this repo?

**Comment by ShuoYangRobotics** [comment]
I just converted int16 to float directly. They can be negative because when the foot restores it’s shape the pressure is smaller than nominal value.

**Comment by cyoahs** [comment]
> I just converted int16 to float directly. They can be negative because when the foot restores it’s shape the pressure is smaller than nominal value.

Got it! ^-^
