### ISSUE TITLE
Joint order in the topic /hardware_a1/joint_foot

### ISSUE THREAD

**Issue by bhyu0924** [ShuoYangRobotics/Cerberus#3]
Hi,

I want to run your dataset to compare the performance.
But I have an inquiry about your dataset.

FL seems "Front Left" but I cannot find any information of number FL0, FL1, FL2.

Is the joint order same as unitree A1 urdf ?
Is this sequence 0(hip), 1(thigh), 2(calf) ?

TIA.

**Comment by ShuoYangRobotics** [comment]
Hi, yes the order you said is right.
